<a href="https://colab.research.google.com/github/mmtaha/BOOTCAMP-EVERIS/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import  train_test_split

In [ ]:
 dados = pd.read_csv("/content/train.csv")

In [ ]:
dados.head()

   Passengerid   Age     Fare  Sex  ...  Embarked  zero.17  zero.18  2urvived
0            1  22.0   7.2500    0  ...       2.0        0        0         0
1            2  38.0  71.2833    1  ...       0.0        0        0         1
2            3  26.0   7.9250    1  ...       2.0        0        0         1
3            4  35.0  53.1000    1  ...       2.0        0        0         1
4            5  35.0   8.0500    0  ...       2.0        0        0         0

[5 rows x 28 columns]

In [ ]:
dados = dados.drop(['name','ticket','cabin','embarked'], axis=1)

KeyError: ignored